### PR TITLE
Fixes regression created in #55

### LINKED ISSUE #55: Polling tentacles need service restarted
Trying to deploy octopus in mass. I find polling tentacles are installed properly, however they always fail their health check until I manually restart the service. 

This is strange because the configure tentacle resource notifies the windows service to restart with a `:delayed` timer, yet it looks like the restart happens before the register action happens. 

```
Recipe: nd-octopus::tentacle
  * octopus_deploy_tentacle[Tentacle] action install
    * remote_file[C:\chef\cache/octopus-tentacle.msi] action create (up to date)
    * windows_package[Octopus Deploy Tentacle] action install (up to date)
     (up to date)
  * octopus_deploy_tentacle[Tentacle] action configure
    * windows_firewall_rule[Octopus Deploy Tentacle] action create (skipped due to only_if)
    * octopus_deploy_tentacle[Tentacle] action install
      * remote_file[C:\chef\cache/octopus-tentacle.msi] action create (up to date)
      * windows_package[Octopus Deploy Tentacle] action install (up to date)
       (up to date)
    * directory[C:\Octopus] action create (up to date)
    * powershell_script[generate-tentacle-cert] action run
      - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/sowen/AppData/Local/Temp/2/chef-script20160817-2116-176koe7.ps1"
    * powershell_script[create-instance-Tentacle] action run
      - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/sowen/AppData/Local/Temp/2/chef-script20160817-2116-1h1q6d6.ps1"
    * powershell_script[configure-tentacle-Tentacle] action run
      - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/sowen/AppData/Local/Temp/2/chef-script20160817-2116-qnlanm.ps1"
    * windows_service[OctopusDeploy Tentacle] action enable (up to date)
    * windows_service[OctopusDeploy Tentacle] action start (up to date)
    * windows_service[OctopusDeploy Tentacle] action restart
      - restart service windows_service[OctopusDeploy Tentacle]

  * octopus_deploy_tentacle[Tentacle] action register
    * powershell_script[register-Tentacle-tentacle] action run
      - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/sowen/AppData/Local/Temp/2/chef-script20160817-2116-1913boz.ps1"

Starting audit phase
```

### PR DESCRIPTION
**Pull request by spuder**
Fixes the regression that 4f788e299a3aae4b96610dcd8ced863640aa40fe introduced in #55 
Also fixes #55 so tentacles no longer require manual restarts before health checks pass. 

```ruby
         * octopus_deploy_tentacle[Tentacle] action configure
           * windows_firewall_rule[Octopus Deploy Tentacle] action create (skipped due to only_if)
           * octopus_deploy_tentacle[Tentacle] action install[2016-08-18T00:01:28+00:00] WARN: Please use the package resource available in Chef Client 12.6.
       windows_package will be removed in the next major version release
       of the Windows cookbook.


             * remote_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/octopus-tentacle.msi] action create (up to date)
             * windows_package[Octopus Deploy Tentacle] action install (up to date)
       (up to date)
           * directory[C:\Octopus] action create (up to date)
           * powershell_script[generate-tentacle-cert] action run (skipped due to not_if)
           * powershell_script[create-instance-Tentacle] action run (skipped due to not_if)
           * powershell_script[configure-tentacle-Tentacle] action run (skipped due to not_if)
           * windows_service[OctopusDeploy Tentacle] action enable (up to date)
           * windows_service[OctopusDeploy Tentacle] action start (up to date)
            (up to date)
         * octopus_deploy_tentacle[Tentacle] action register
           * powershell_script[register-Tentacle-tentacle] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20160818-2168-1j55eel.ps1"
           * windows_service[OctopusDeploy Tentacle] action nothing (skipped due to action :nothing)
           * windows_service[OctopusDeploy Tentacle] action restart
             - restart service windows_service[OctopusDeploy Tentacle]

```

Green checkmark means health check passed. 

screenshot 2016-08-17 18 09 25

The git history is now a little messy. If you prefer, you could revert #55 and we can combine it with #57. Otherwise it should be good as is.

### CODE REVIEW

File: providers/tentacle.rb [hunk 1]
```diff
@@ -168,7 +169,11 @@
     notifies :restart, "windows_service[#{service_name}]", :delayed
   end
 
-  new_resource.updated_by_last_action(actions_updated?([register_instance]))
+  service = windows_service service_name do
```
Comment (brentm5) [inline providers/tentacle.rb]: I believe we can ignore this part because if the action above happens then the restart will happen and therefore the resource will be updated.

**Comment by brentm5** [comment]
No need to revert.   Just want to make sure its fixed before publishing this to supermarket.

File: providers/tentacle.rb (hunk 1 above)
Comment (spuder) [inline providers/tentacle.rb]: Not sure I follow, are you saying change this:

   new_resource.updated_by_last_action(actions_updated?([register_instance, service]))

to this? 

    new_resource.updated_by_last_action(actions_updated?([register_instance]))

Comment (brentm5) [inline providers/tentacle.rb]: Yup that is correct.  That service resource does not need to be included as it is dependent on the tentacle.  If it was also performing an action by default I would include it but in this case it is only being notified by the existing resource.

**Comment by spuder** [comment]
Removed the service from new_resource.updated_by_last_action

Manually verified it works

I do notice that it sends 2 notifications to restart, I don't think there is any way of avoiding that without a large refactor. While not ideal, It shouldn't harm anything. 


```
         * octopus_deploy_tentacle[Tentacle] action configure
           * windows_firewall_rule[Octopus Deploy Tentacle] action create (skipped due to not_if)
           * octopus_deploy_tentacle[Tentacle] action install[2016-08-18T01:06:42+00:00] WARN: Please use the package resource available in Chef Client 12.6.
       windows_package will be removed in the next major version release
       of the Windows cookbook.


             * remote_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache/octopus-tentacle.msi] action create (up to date)
             * windows_package[Octopus Deploy Tentacle] action install (up to date)
       (up to date)
           * directory[C:\Octopus] action create
             - create new directory C:\Octopus
           * powershell_script[generate-tentacle-cert] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20160818-1092-1foxu5g.ps1"
           * powershell_script[create-instance-Tentacle] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20160818-1092-skswk5.ps1"
           * powershell_script[configure-tentacle-Tentacle] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20160818-1092-od3wir.ps1"
           * windows_service[OctopusDeploy Tentacle] action enable (up to date)
           * windows_service[OctopusDeploy Tentacle] action start (up to date)
           * windows_service[OctopusDeploy Tentacle] action restart
             - restart service windows_service[OctopusDeploy Tentacle]

         * octopus_deploy_tentacle[Tentacle] action register
           * powershell_script[register-Tentacle-tentacle] action run
             - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20160818-1092-l5ybvu.ps1"
           * windows_service[OctopusDeploy Tentacle] action nothing (skipped due to action :nothing)
           * windows_service[OctopusDeploy Tentacle] action restart
             - restart service windows_service[OctopusDeploy Tentacle]
```

**Comment by spuder** [comment]
👍 
Will there be a 0.6.3 ?

**Comment by brentm5** [comment]
Published
